### ISSUE TITLE
Missing Cape on Mojang_Classic Cape

### ISSUE THREAD

**Issue by kahzukie** [SourceCouncil/Minecraft-Bedrock-Capes#1]
On the skins.json, the name of the cape file is wrong, it says Mojang_Classic.png, but the file name is Mojang_Classic_Cape.png
```json
    {
      "localization_name": "MojangCape(Classic)",
      "geometry": "geometry.humanoid.custom",
      "texture": "skin.png",
      "cape": "Mojang_Classic.png",
      "type": "free"
    },
```

**Comment by BlckMg** [comment]
Fixed on commit [c30f22acd6207a70c63e1a266ab0e35795a11a30](https://github.com/SourceCouncil/Minecraft-Bedrock-Capes/commit/c30f22acd6207a70c63e1a266ab0e35795a11a30)
